### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by GiggleLiu**
There are some package versions too old.

### CODE REVIEW

**Comment by GiggleLiu** [comment]
It looks like the CI is not running.

**Comment by dlfivefifty** [comment]
Thanks for this!

It's standard to only test on the earliest support version 1.0 and the latest version which is indicated by 1. I pushed the change.

**Comment by dlfivefifty** [comment]
It looks like this picked up a bug in Julia 1.6. Are you able to fix it?

**Comment by GiggleLiu** [comment]
I just tried fixing it. Can you please approve running the workflow? thanks~

**Comment by dlfivefifty** [comment]
Thanks! If you bump the patch version I can merge and tag.

(If you feel like getting the codecov up first feel free, but not required)

**Comment by GiggleLiu** [comment]
Tests added, the version bumps to 0.5.1. Cheers~

**Comment by dlfivefifty** [comment]
Please remove the Manifest.toml and add it to .gitignore

**Comment by GiggleLiu** [comment]
oops, sorry, removed.

**Comment by GiggleLiu** [comment]
There is a failing job, looks like irrelevant to this pr.

**Comment by dlfivefifty** [comment]
Always has to be one 🙄

**Pull request merged**
